### ISSUE TITLE
fill out DESCRIPTION file and friends

### ISSUE THREAD

**Issue by juniperlsimonis** [jms5151/uh-noaa-shiny-app#8]
See https://r-pkgs.org/description.html 

- [x] Title
- [x] Authors (names, roles, ORCID #s)
- [x] License 
- [x] Also add LICENSE file
- [x] Description
- [x] url

**Comment by jms5151** [comment]
**Title**: Multi-Factor Coral Disease Forecast data explorer

Authors@R: person("Caldwell", "Jamie", email = "jamie.sziklay@gmail.com",
  role = c("aut", "cre"))

**url**: https://coraldisease.com/

**Description**: A shiny application to visualize and explore near term coral disease forecasts associated with the NOAA Coral Reef Watch experimental product, 'Multi-Factor Coral Disease Forecast', developed in collaboration with researchers from the University of Hawaii at Manoa (USA) and James Cook University (Australia). The application has four components: 1) visualizations through space and time of Pacific coral reef diseases; 2) scenarios for refining predictions or assessing interventions; 3) historical data records that were used to build the disease risk models; and 4) supportiving information about the product. 

**License**: "THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."
